sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  - DOCKER_IMAGE=2741/rso-customers:1.0

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - docker login -u=2741 -p=basicto
  - docker push "$DOCKER_IMAGE"