version: "3"
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer
  rso-customers:
    image: 2741/mojaprvaslika
    ports:
      - 8080:8080
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://localhost:5432/customer

    depends_on:
      - postgres