kumuluzee:
  name: Kopj
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  #datasources:
   #- jndi-name: jdbc/CustomersDS
    # connection-url: jdbc:postgresql://localhost:5432/customer
     #username: postgres
     #password: postgres

  #config:
   # etcd:
    #  hosts:
  cors-filter:
    servlet:
      allow-origin: "*"
rest-properties:
  external-services:
    order-service:
      enabled: true
